### ISSUE TITLE
Suggestions here!

### ISSUE THREAD

**Issue by Lebon14** [zsty/quoteplant#2]
"When you think about it, GoldenEye 007 is all about eggplants: Eggplant Dam, Eggplant Facility, Eggplant Runaway, Eggplant Surface: The First, Eggplant Bunker: The First, Eggplant Silo, Eggplant Frigate, Eggplant Surface: The Second, Eggplant Bunker: The Second, Eggplant Statue, Eggplant Archive, Eggplant Streets, Eggplant Depot, Eggplant Train, Eggplant Jungle, Eggplant Control, Eggplant Caverns, Eggplant Cradle, Eggplant Aztec and Egyptian Eggplant. If that's not proof that GoldenEye 007 is not about eggplants, I don't know what would prove it. So much, I wonder why the game wasn't named "GoldenEggplant 007"."

**Comment by byhemechi** [comment]
Sounds good, PR?

**Comment by Lebon14** [comment]
PR? I'm just trying to be funny :)

**Comment by byhemechi** [comment]
This whole thing is stupid, this isn't the worst :wink:

**Comment by Lebon14** [comment]
I know this is stupid. This copypasta is just in pure fun. :P
