### ISSUE TITLE
You should not store you oauth key in your repo :)

### ISSUE THREAD

**Issue by thepureinx000** [zsty/quoteplant#5]
Instead of this:
`identity: {
    username: 'quoteplant',
    password: 'oauth:vecsqwidq6nlc8zvt4mujc6e6np7ul'
  }
}`
You should use something like this:
`const config = require('./config')`
`  identity: {
    username: config.username,
    password: config.oauth
  }
}`
Of course you shouldn't put config file into repo too :)

**Comment by byhemechi** [comment]
i am aware of this, i fixed it, but forgot to push. thanks for reminding :)
